name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, '[Gradle Release Plugin]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout code
      - uses: gradle/wrapper-validation-action@v1
        name: Validate Gradle wrapper
      - uses: actions/cache@v1
        name: Cache Gradle wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlew-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-
      - uses: actions/cache@v1
        name: Cache dependencies
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: |
          ./gradlew build
